Repository 100-Devs-1-Game/All-the-Incrementals, pull requests merged in 2025-07, with the labels that each got.

#7 Add pre-commit hook for snake_case directories and files
  .hooks/check_dir_names.py
  .pre-commit-config.yaml
  scripts/hooks_disable.sh
  scripts/hooks_enable.sh
  scripts/test_precommit.sh
Labels: devops

#30 Update README with channel for requesting GitHub repo access
  README.md
Labels: documentation

#31 Update README with channel for requesting GitHub repo access
  README.md
Labels: documentation

#33 Update LICENSE file to point out dual licensing
  LICENSE
Labels: documentation

#35 Update contributors list
  README.md
Labels: documentation

#69 Added default theme, default scene, placeholder icon, default game resolution
  src/assets/icons/placeholder.png
  src/assets/icons/placeholder.png.import
  src/global/theme.tres
  src/modules/main/main.gd
  src/modules/main/main.gd.uid
  src/modules/main/main.tscn
  src/project.godot
Labels: enhancement

#76 Use gl_compatibility renderer
  src/project.godot
Labels: enhancement

#92 Post unassigned tasks to Discord
  .github/workflows/tasks.yml
Labels: devops

#93 Add placeholder skeleton for game (splash screens, menus, overworld, minigames, settlements, altars)
  README.md
  src/assets/icons/basket.png
  src/assets/icons/basket.png.import
  src/assets/icons/placeholder.png
  src/modules/credits/credits.tscn
  src/modules/gallery/gallery.tscn
  src/modules/main/main.gd
  src/modules/main/main.tscn
  src/modules/main/splash_one.tscn
  src/modules/main/splash_two.tscn
  src/modules/main/splash_utils.gd
  src/modules/main/splash_utils.gd.uid
  src/modules/menu/extras.tscn
  src/modules/menu/main_menu.tscn
  src/modules/menu/settings.tscn
  src/modules/minigame/earth_potato_herding/earth_potato_herding.tscn
  src/modules/minigame/earth_towers/earth_towers.tscn
  src/modules/minigame/fire_cooking/fire_cooking.tscn
  src/modules/minigame/fire_fighters/fire_fighters.tscn
  src/modules/minigame/water_diving/water_diving.tscn
  src/modules/minigame/water_fishing/water_fishing.tscn
  src/modules/minigame/wind_platformer/wind_platformer.tscn
  src/modules/minigame/wind_rhythm/wind_rhythm.tscn
  src/modules/overworld/overworld.tscn
  src/modules/placeholder/placeholder.gd
  src/modules/placeholder/placeholder.gd.uid
  src/modules/placeholder/placeholder.tscn
  src/modules/placeholder/placeholder_button.gd
  src/modules/placeholder/placeholder_button.gd.uid
  src/modules/settlement/breezekiln/breezekiln.tscn
  src/modules/settlement/breezekiln/fire_altar/fire_altar.tscn
  src/modules/settlement/breezekiln/wind_altar/wind_altar.tscn
  src/modules/settlement/clayport/clayport.tscn
  src/modules/settlement/clayport/earth_altar/earth_altar.tscn
  src/modules/settlement/clayport/water_altar/water_altar.tscn
  src/project.godot
Labels: enhancement

#110 Move modules/ui/credits into modules/credits, add start signal
  src/global/event_bus.gd
  src/modules/credits/credits.gd
  src/modules/credits/credits.gd.uid
  src/modules/credits/credits.tscn
  src/modules/credits/credits_placeholder.tscn
  src/modules/main/main.tscn
  src/modules/ui/credits/credits.gd.uid
  src/modules/ui/credits/credits.tscn
Labels: enhancement

#113 Set Panku output overlay to be hidden by default
  src/addons/panku_console/default_panku_config.cfg
Labels: bug

#115 Fixed spelling error in game name, removed unused var in placeholder
  scripts/godot_user_folder.sh
  src/addons/panku_console/default_panku_config.cfg
  src/addons/panku_console/modules/general_settings/module.gd
  src/addons/panku_console/modules/general_settings/opt.gd
  src/modules/credits/credits_placeholder.tscn
  src/modules/placeholder/placeholder.gd
  src/project.godot
Labels: bug, refactor

#116 Add helpful hints precommit hook
  .hooks/helpful_hints.py
  .pre-commit-config.yaml
Labels: devops

#118 Update Art contributors list
  README.md
  src/modules/credits/credits.tscn
Labels: bug, documentation

#121 Simple Text Popup Addition
  src/modules/minigame/common/floating_text/float_text.gd
  src/modules/minigame/common/floating_text/float_text.gd.uid
  src/modules/minigame/common/floating_text/float_text.tscn
  src/modules/minigame/common/floating_text/floating_text_system.tscn
  src/modules/minigame/common/floating_text/floating_text_util.gd
  src/modules/minigame/common/floating_text/floating_text_util.gd.uid
Labels: enhancement
