Repository 100-Devs-1-Game/All-the-Incrementals, pull requests merged in 2025-08, with the labels that each got.

#163 Add documentation to the RngUtils class and methods.
  src/global/rng_utils.gd
Labels: documentation

#164 Use RngUtils and DebugPopup in Fire Fighters minigame
  src/global/event_bus.gd
  src/global/scene_loader.gd
  src/modules/debug/debug_popup.gd
  src/modules/minigame/common/base_minigame.gd
  src/modules/minigame/common/settlement_data.gd
  src/modules/minigame/common/settlement_data.gd.uid
  src/modules/minigame/fire_fighters/fire_fighters.tscn
  src/modules/minigame/fire_fighters/fire_fighters_mingame.gd
  src/modules/minigame/fire_fighters/util/utils.gd
  src/modules/settlement/breezekiln/breezekiln.gd
  src/modules/settlement/breezekiln/breezekiln.gd.uid
  src/modules/settlement/breezekiln/breezekiln.tscn
Labels: enhancement

#166 Fixes bug in variable name in fire fighters script
  src/global/scene_loader.gd
  src/modules/minigame/common/base_minigame.gd
Labels: bug

#167 Replace Placeholder class with DebugPopup
  src/modules/debug/debug_button.gd
  src/modules/debug/debug_popup.gd
  src/modules/debug/debug_popup.tscn
  src/modules/menu/main_menu.tscn
  src/modules/minigame/fire_fighters/fire_fighters.tscn
  src/modules/settlement/breezekiln/breezekiln.tscn
Labels: refactor

#170 Add quit_game() to base minigame for use by debug popup
  src/modules/minigame/common/base_minigame.gd
  src/modules/minigame/example/minigame.tscn
  src/modules/minigame/fire_fighters/fire_fighters.tscn
Labels: enhancement

#171 Update MainMenu scene to use DebugPopup instead of Placeholder
  src/modules/debug/debug_popup.gd
  src/modules/menu/main_menu.gd
  src/modules/menu/main_menu.tscn
Labels: refactor

#176 Use DebugPopup instead of Placeholder in empty minigame scenes
  src/modules/minigame/earth_towers/earth_towers.tscn
  src/modules/minigame/fire_cooking/fire_cooking.tscn
  src/modules/minigame/water_diving/water_diving.tscn
  src/modules/minigame/water_target_fishing/water_target_fishing.tscn
  src/modules/minigame/wind_platformer/wind_platformer.tscn
  src/modules/minigame/wind_rhythm/wind_rhythm.tscn
Labels: refactor

#173 Module/settings functionality
  src/global/blur.gdshader
  src/global/blur.gdshader.uid
  src/modules/audio/default_bus_layout.tres
  src/modules/menu/main_menu.tscn
  src/modules/settings/game_settings.gd
  src/modules/settings/game_settings.gd.uid
  src/modules/settings/rebinding/rebinder.gd
  src/modules/settings/rebinding/rebinder.gd.uid
  src/modules/settings/rebinding/rebinder.tscn
  src/modules/settings/settings.gd
  src/modules/settings/settings.gd.uid
  src/modules/settings/settings.tscn
  src/project.godot
Labels: enhancement

#196 Allow local override.cfg file to override project settings
  .gitignore
  src/project.godot
Labels: enhancement

#202 Fix error about duplicate uid
  src/modules/overworld_map/overworld_map.tscn
Labels: bug

#203 Allow fire fighters minigame to start directly
  src/modules/minigame/fire_fighters/fire_fighters.tscn
Labels: enhancement

#199 Use tree for debug popup
  src/modules/debug/debug_minigame_upgrades.gd
  src/modules/debug/debug_minigame_upgrades.gd.uid
  src/modules/debug/debug_minigame_upgrades.tscn
  src/modules/debug/debug_popup.gd
  src/modules/debug/debug_popup.tscn
  src/modules/menu/main_menu.tscn
  src/modules/minigame/common/base_minigame.gd
  src/modules/minigame/example/minigame.tscn
Labels: enhancement, refactor

#209 Remove unused variable
  src/modules/settings/game_settings.gd
Labels: refactor

#210 Make DebugPopup more easily extensible
  src/modules/debug/README.md
  src/modules/debug/debug_minigame_upgrades.tscn
  src/modules/debug/debug_popup.gd
  src/modules/minigame/common/base_minigame.gd
  src/modules/minigame/common/debug/clayport.tres
  src/modules/minigame/common/debug/debug_minigame_upgrades.gd
  src/modules/minigame/common/debug/debug_minigame_upgrades.gd.uid
  src/modules/minigame/common/debug/debug_minigame_upgrades.tscn
  src/modules/minigame/common/debug/exit_minigame.tres
  src/modules/minigame/common/debug/main_menu.tres
  src/modules/minigame/common/debug/quit_game.tres
  src/modules/minigame/common/debug/settings.tres
  src/modules/minigame/earth_potato_herding/earth_potato_herding.tscn
  src/modules/minigame/example/minigame.tscn
  src/modules/minigame/fire_fighters/fire_fighters.tscn
Labels: refactor

#212 Add debug upgrades to wind platformer
  src/modules/minigame/wind_platformer/wind_platformer.gd
  src/modules/minigame/wind_platformer/wind_platformer.tscn
Labels: enhancement

#216 Launch more minigames with settlement context
  src/modules/minigame/earth_potato_herding/earth_potato_herding.tscn
  src/modules/minigame/earth_towers/data/earth_towers_data.tres
  src/modules/minigame/earth_towers/earth_towers.gd
  src/modules/minigame/earth_towers/earth_towers.gd.uid
  src/modules/minigame/earth_towers/earth_towers.tscn
  src/modules/minigame/fire_cooking/data/fire_cooking_data.tres
  src/modules/minigame/fire_cooking/fire_cooking.gd
  src/modules/minigame/fire_cooking/fire_cooking.gd.uid
  src/modules/minigame/fire_cooking/fire_cooking.tscn
  src/modules/minigame/fire_fighters/fire_fighters.tscn
  src/modules/minigame/water_diving/data/water_diving_data.tres
  src/modules/minigame/water_diving/water_diving.gd
  src/modules/minigame/water_diving/water_diving.gd.uid
  src/modules/minigame/water_diving/water_diving.tscn
  src/modules/minigame/water_target_fishing/data/water_target_fishing_data.tres
  src/modules/minigame/water_target_fishing/water_target_fishing.gd
  src/modules/minigame/water_target_fishing/water_target_fishing.gd.uid
  src/modules/minigame/water_target_fishing/water_target_fishing.tscn
  src/modules/minigame/wind_platformer/wind_platformer.tscn
  src/modules/minigame/wind_rhythm/data/wind_rhythm_data.tres
  src/modules/minigame/wind_rhythm/wind_rhythm.gd
  src/modules/minigame/wind_rhythm/wind_rhythm.gd.uid
  src/modules/minigame/wind_rhythm/wind_rhythm.tscn
  src/modules/overworld_locations/breezekiln/breezekiln.gd
  src/modules/overworld_locations/breezekiln/breezekiln.tscn
  src/modules/overworld_locations/clayport/clayport.gd
  src/modules/overworld_locations/clayport/clayport.tscn
  src/modules/overworld_locations/clayport/clayport_data.tres
Labels: refactor

#229 Fix parsing error when the Panku addon is disabled
  src/modules/debug/debug_popup.gd
Labels: bug

#233 Fix narrowing conversion error
  src/modules/upgrade/base_upgrade.gd
Labels: bug

#242 Fix wrong path in resource for water target fishing minigame data
  src/modules/overworld_locations/clayport/clayport.tscn
Labels: bug

#249 Add code architecture documentation and notes
  docs/architecture.md
Labels: documentation

#275 Fix conflicing function name
  src/modules/minigame/earth_potato_herding/earth_potato_herding.gd
  src/modules/minigame/earth_potato_herding/eph_adult/eph_adult.gd
Labels: bug

#270 Create Resource Resaver Plugin
  src/addons/panku_console/common/lynx_window2/lynx_window_shader_material.tres
  src/addons/resource_resave/README.md
  src/addons/resource_resave/plugin.cfg
  src/addons/resource_resave/plugin.gd
  src/addons/resource_resave/plugin.gd.uid
  src/addons/upgrade_tree/test/test_upgrade_tree_minigame_data.res
  src/addons/upgrade_tree/test/upgrades/upgrade_test_one.tres
  src/addons/upgrade_tree/test/upgrades/upgrade_test_two.tres
  src/modules/minigame/earth_potato_herding/eph_upgrades/nutritious_potato_upgrade.tres
  src/modules/minigame/earth_potato_herding/eph_upgrades/spirit_keeper_brightness.tres
  src/modules/minigame/earth_potato_herding/eph_upgrades/spirit_keeper_speed.tres
  src/modules/minigame/example/upgrades/upgrade_speed_algorithmic.tres
  src/project.godot
Labels: devops
